import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.43.227/symfony/web/index.php/auth/login');
  await page.locator('#txtUsername').click();
  await page.locator('#txtUsername').fill('zubbyik');
  await page.getByText('LOGIN Panel Username Password').click();
  await page.locator('#txtPassword').click();
  await page.locator('#txtPassword').fill('!1Winner75');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await expect(page.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PIM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Recruitment' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Info' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Performance' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Dashboard' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Directory' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Maintenance' })).toBeVisible();
  await expect(page.locator('#menu_admin_viewAdminModule')).toContainText('Admin');
  await expect(page.locator('#menu_pim_viewPimModule')).toContainText('PIM');
  await expect(page.locator('#menu_leave_viewLeaveModule')).toContainText('Leave');
  await expect(page.locator('#menu_time_viewTimeModule')).toContainText('Time');
  await expect(page.locator('#menu_recruitment_viewRecruitmentModule')).toContainText('Recruitment');
  await expect(page.locator('#menu_pim_viewMyDetails')).toContainText('My Info');
  await expect(page.locator('#menu__Performance')).toContainText('Performance');
  await expect(page.locator('#menu_dashboard_index')).toContainText('Dashboard');
  await expect(page.locator('#menu_directory_viewDirectory')).toContainText('Directory');
  await expect(page.locator('#wrapper')).toContainText('Maintenance');
  await expect(page.locator('#MP_link')).toContainText('Marketplace');
  await expect(page.locator('#Subscriber_link')).toContainText('Subscribe');
  await expect(page.locator('#welcome')).toContainText('Welcome Ikman');
  await expect(page.getByRole('link', { name: 'Welcome Ikman' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Assign Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Leave List' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Timesheets' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Apply Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Leave' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My Timesheet' })).toBeVisible();
  await expect(page.locator('#dashboard-quick-launch-panel-menu_holder')).toContainText('Assign Leave');
  await expect(page.locator('#dashboard-quick-launch-panel-menu_holder')).toContainText('Leave List');
  await expect(page.locator('#dashboard-quick-launch-panel-menu_holder')).toContainText('Timesheets');
  await expect(page.locator('#dashboard-quick-launch-panel-menu_holder')).toContainText('Apply Leave');
  await expect(page.locator('#dashboard-quick-launch-panel-menu_holder')).toContainText('My Leave');
  await expect(page.locator('#dashboard-quick-launch-panel-menu_holder')).toContainText('My Timesheet');
  await expect(page.locator('canvas').nth(1)).toBeVisible();
  await expect(page.locator('#div_legend_pim_employee_distribution_legend')).toContainText('Not assigned to Subunits');
  await expect(page.locator('#task-list-group-panel-menu_holder')).toContainText('No Records are Available');
  await expect(page.getByText('OrangeHRM 4.3.5 © 2005 - 2024')).toBeVisible();
  await expect(page.locator('#footer')).toContainText('OrangeHRM 4.3.5 © 2005 - 2024 OrangeHRM, Inc. All rights reserved.');
});